spring:
  profiles:
    active: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    try-it-out-enabled: true


kis:
  api:
    app-key: ${KIS_APPKEY} # 개인 한국 투자 증권 APP KEY
    app-secret: ${KIS_APPSECRET} # 개인 한국 투자 증권 APP SECRET
